version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=docker-secret-key-change-in-production
      - DATABASE_URL=postgresql://bankuser:bankpass@db:5432/securebank
      - TXN_LIMIT_SINGLE=5000
      - TXN_LIMIT_DAILY=10000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - banknet

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=securebank
      - POSTGRES_USER=bankuser
      - POSTGRES_PASSWORD=bankpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - banknet

volumes:
  postgres_data:

networks:
  banknet:
    driver: bridge
